# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka  

spring:
  config:
    import:
    - configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-66345900.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
           provider: okta
           authorization-grant-type: client_credentials
           scope: internal
           client-id: 0oaii6nrr5OYHJUQL5d7
           client-secret: hgACUeHHBh06uyiM490vEnKWyGx75GgLUfUgDwchlpfJJyM1Sgj9rl68oOvjFB55
        provider:
         okta:
            issuer-uri: https://dev-66345900.okta.com/oauth2/default 
                  
  # profiles:
  #    active: prod

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: always

resilience4j:
  # circuitbreaker:
  #   instances:
  #     ratingHotelBreaker:
  #      register-health-indicator: true
  #      event-consumer-buffer-size: 10
  #      failure-rate-threshold: 50
  #      minimum-number-of-calls: 5
  #      automatic-transition-from-open-to-half-open-enabled: true
  #      wait-duration-in-open-state: 60s
  #      permitted-number-of-calls-in-half-open-state: 3
  #      sliding-window-size: 10
  #      sliding-window-type: COUNT_BASED  
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
       register-health-indicator: true
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 5
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 60s
       permitted-number-of-calls-in-half-open-state: 3
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED 
    instances:
       ratingHotelBreaker:
        base-config: default
       ratingHotelListBreaker:
        base-config: default  
        
  retry:
   retry-aspect-order: 2
   instances:
    ratingHotelService:
     maxAttempts: 5
     waitDuration: 15s
  rateLimiter:
   instances:
    ratingHotelLimiter:
     limitRefreshPeriod: 4s
     limitForPeriod: 2
     timeoutDuration: 2s

okta:
  oauth2:
    issuer: https://dev-66345900.okta.com/oauth2/default
    audience: api://default
        

   
                      



